### ISSUE TITLE
Link.xml is missing from package 2.7.0

### ISSUE THREAD

**Issue by ArisTsevrenis** [heroiclabs/nakama-unity#100]
https://github.com/heroiclabs/nakama-unity/blob/master/Packages/Nakama/Editor/link.xml

**Comment by lugehorsam** [comment]
@ArisTsevrenis how are you including the package? Via the Asset Store or via the Unity Package Manager?

**Comment by lugehorsam** [comment]
@ArisTsevrenis in both cases, the `link.xml` is included when I test manually. Please let me know what other conditions you may be triggering to reproduce this issue.
