### ISSUE TITLE
Authentication timeout on WebGL is fixed at 15 seconds

### ISSUE THREAD

**Issue by DaveOak** [heroiclabs/nakama-unity#103]
Changing the timeout in config.yml works for Android and iOS builds but makes no difference to WebGL builds that use UnityWebRequestAdapter. The timeout appears to be 15 seconds.

For context, a Facebook player with > 1000 playing friends causes a long delay (approx 17 seconds) on authentication while the friends list is imported.

**Comment by lugehorsam** [comment]
@DaveOak Thanks for filing this issue. This is now fixed in this patch: https://github.com/heroiclabs/nakama-unity/commit/4d4240c00ffd35733cb314c1ced6393a69208bdb

You can use it now using the instructions in the README or wait for a Unity Asset Store release if you're using our package that way, though the former approach is recommended.

**Comment by DaveOak** [comment]
Hi Luke

Thanks for the fix. I’m unsure of how to install it though. I tried adding this line to my manifest.json but the build now hangs at the authenticate call.

"com.heroiclabs.nakama-unity": "https://github.com/heroiclabs/nakama-unity.git?path=/Packages/Nakama#4d4240c00ffd35733cb314c1ced6393a69208bdb”

I previously downloaded and installed the 2.7.0 unity package.

Thanks.

**Comment by lugehorsam** [comment]
Hey Dave, it looks like you imported it correctly. Is the hanging still only just for WebGL builds? Could you share the piece of code that hangs?

**Comment by DaveOak** [comment]
Hi Luke, thanks for confirming my approach was OK. The hanging problem turned out to be a bug in my own code. The timeout now works correctly when I set _client.Timeout in my code before authenticating.

**Comment by lugehorsam** [comment]
🎉
