### ISSUE TITLE
Leaving the Match while loading the scene

### ISSUE THREAD

**Issue by ragavendranbala** [heroiclabs/nakama-unity#110]
I have installed nakama on my digital ocean server without any server side scripting. It's working fine with room join, login and others. But I'm facing a major issue where the joined match gets closed on others phone, while I load another scene on my phone. I'm using unity main thread dispatcher to load the scene. Using unity 2019.4.18 LTS.

Kindly get me to fix this issue

**Comment by lugehorsam** [comment]
Hey @ragavendranbala, we'll need a more specific question since there are many reasons why a room can get closed when changing a scene. There's nothing in the Nakama Unity client that ties a match to a scene -- the socket persists through scenes.

**Comment by ragavendranbala** [comment]
I have created a match making pool and search for opponents with some custom properties and I'm checking for opponents joins. once the Required number of opponents have joined on my game by getting the onmatched callback, I'm immediately loading the Scene with those opponents info. inbetween this loading, Most of the times, I'm getting an another presence update event that the user have left the game. and also. while rejoining the match with the saved matched ID on playerprefs. the other users getting the presence update 2 times that the user have joined and left. 

@lugehorsam  hopefully this information is good to investigate further.

**Comment by lugehorsam** [comment]
@ragavendranbala it's not really possible to tell what the issue could be based on your description. It's highly dependent on how you've written your code.  If you share relevant sections such as the matchmaker call, the match join handler, the core match loop and your `LeaveMatch` logic, I'd be happy to take a look.

I think you should also take a look at our sample project which successfully loads a "match scene" which I believe is similar to your intent here: https://github.com/heroiclabs/unity-sampleproject
