### ISSUE TITLE
KeyNotFound Exception

### ISSUE THREAD

**Issue by zfand** [heroiclabs/nakama-unity#111]
Hi Nakama, 

 Our game is using Nakama Unity version 2.4.0 and we see the following exception:
```
KeyNotFoundException The given key was not present in the dictionary. 
    <00000000000000000000000000000000> System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item(TKey key)
    <00000000000000000000000000000000> Nakama.UnityWebRequestAdapter+<SendRequest>d__11.MoveNext()
    <00000000000000000000000000000000> UnityEngine.SetupCoroutine.InvokeMoveNext(System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress)
```

It looks like the culprit is this [line](https://github.com/heroiclabs/nakama-unity/blob/master/Packages/Nakama/Runtime/UnityWebRequestAdapter.cs#L129).

Could you please update this function to check if the dictionary has the key before accessing it? Thank you!

**Comment by lugehorsam** [comment]
Thanks @zfand, we'll create a patch release on Github today with a fix.

**Comment by lugehorsam** [comment]
We've done a new release with this fix: https://github.com/heroiclabs/nakama-unity/releases/tag/v2.8.1

You can upgrade to it via an entry in your project's `manifest.json`:

`"com.heroiclabs.nakama-unity": "https://github.com/heroiclabs/nakama-unity.git?path=/Packages/Nakama#v2.8.1"`

**Comment by lugehorsam** [comment]
Edit: I've also included the .unitypackage as part of the release binaries.
