### ISSUE TITLE
ListTournamentRecordsAroundOwnerAsync won't return record ranked 1st.

### ISSUE THREAD

**Issue by DaveOak** [heroiclabs/nakama-unity#112]
I'm calling ListTournamentRecordsAroundOwnerAsync in the Unity SDK and it won't return the record ranked 1st. E.g, if the owner is ranked above 50th in the tournament and I ask for 100 records around the owner, I will get the records ranked 2 to 101. This is even true if the owner is ranked 1, and is missed from the list.

**Comment by lugehorsam** [comment]
This has been resolved in Nakama 3.3.
