### ISSUE TITLE
UnityWebRequest.isHttpError is deprecated 

### ISSUE THREAD

**Issue by kaancetinkayasf** [heroiclabs/nakama-unity#115]
In file UnityWebRequestAdapter.cs file script uses a deprecated UnityWebRequest method.

**Comment by kaancetinkayasf** [comment]
#116 Linked a pull request

**Comment by kaancetinkayasf** [comment]
Linked PR to the issue

**Comment by kaancetinkayasf** [comment]
This problem only occurs in the newer versions of Unity

**Comment by lugehorsam** [comment]
This has been resolved on master and will be incorporated into the next release: https://github.com/heroiclabs/nakama-unity/commit/402e31bb84bebcfa23644d39de95dce9af034300
