### ISSUE TITLE
UpdateAccountAsync it does not handle metadata

### ISSUE THREAD

**Issue by Molder72** [heroiclabs/nakama-unity#118]
The function reflects almost all parameters with respect to its server-side function, except metadata.
From documentation the c++ SDK and some other SDK accept metadata, c# SDK does not.

At the moment to add metadata to the Account/User, I have to call an RPC function right after UpdateAccountAsync,
not very elegant.

expected:
Task UpdateAccountAsync(ISession session, string username, string displayName = null, string avatarUrl = null, string langTag = null, string location = null, string timezone = null, **string metadata = null** );

add 
string metadata = null 
as a parameter

**Comment by lugehorsam** [comment]
Hey @Molder72 thanks for filing this. Metadata is intended to only be set on the server and not the client. So your current RPC pattern sounds correct.

The C++ client supporting it is an error.
