### ISSUE TITLE
Memory leak with UnityWebRequestAdapter?

### ISSUE THREAD

**Issue by msklywenn** [heroiclabs/nakama-unity#120]
Since updating to 3.1.1 and/or using `UnityWebRequestAdapter` so that WebGL builds work, I have been randomly getting this error message: `A Native Collection has not been disposed, resulting in a memory leak. Enable Full StackTraces to get more details.`

Unfortunately, enabling full stack traces everywhere still wouldn't give me a callstack...

I searched the code for a bit and I think I nailed it down to a `UnityWebRequest` in `UnityWebRequestAdapter` not being Disposed. I just added `www.Dispose();` to the end of the `SendRequest` coroutine and all *seems* fine now. I'm not exactly sure if that is the right spot though.

**Comment by lugehorsam** [comment]
Thanks for catching this @msklywenn. I've resolved this in master (https://github.com/heroiclabs/nakama-unity/commit/0eb5d0afa12099097fe8edbd48314fb7e0a0e0fb) and will incorporate it into the next release.
