### ISSUE TITLE
UnityWebRequest.isNetworkError is obsolete

### ISSUE THREAD

**Issue by MrW1zard** [heroiclabs/nakama-unity#121]
UnityWebRequest.isNetworkError is obsolete and is triggering a compile warning in Unity 2020.3.x

Warning CS0618: 'UnityWebRequest.isNetworkError' is obsolete: 'UnityWebRequest.isNetworkError is deprecated. Use (UnityWebRequest.result == UnityWebRequest.Result.ConnectionError) instead.' (CS0618)

**Comment by lugehorsam** [comment]
Hey @MrW1zard are you on v3.1.1? We've fixed the warning there.

Thanks.

**Comment by MrW1zard** [comment]
Yes, that is the version throwing the error;
3.1.0 (Current) - released on August 12, 2021

**Comment by lugehorsam** [comment]
@MrW1zard v3.1.1 is our latest, not v3.1.0. You can get it via Unity Package Manager if it isn't in the asset store at the moment.
