### ISSUE TITLE
There is no callback for requesting data when the network is disconnected on SDK V3.1.1

### ISSUE THREAD

**Issue by xiaoleMu** [heroiclabs/nakama-unity#123]
We upgraded Nakama (the Game SDK) from "version": "2.9.3" to "version": "3.1.1". The initializing Nakama client interface is changed:

- _ client = new Client (serverSettings.scheme, serverSettings.host, serverSettings.port, serverSettings.serverKey, autoRefreshSession) ;
+ _client = new Client (serverSettings.scheme, serverSettings.host, serverSettings.port, serverSettings.serverKey, HttpRequestAdapter.WithGzip(), autoRefreshSession) ;

Cause a problem:

When the data is requested in the network disconnected state, the failure of the request will not be fed back immediately,
the timeout does not take effect either, and there is no response call back after timeout.

In the previous version : "2.9.3". There is no such problem.

Steps to reproduce -
1. Open the game
2. Turn off mobile network and WiFi after AuthenticateDeviceAsync
3. use <Clinet.ListUsersStorageObjectsAsync> to request storage data
Unity 2019.2.17f1

the first request, we can get an error after time out: A task was canceled.
the second request, there will be no response fed back.

Can you please check，thanks.

**Comment by novabyte** [comment]
A new release of the Unity client is available: https://github.com/heroiclabs/nakama-unity/releases/v3.3.0
Please test it and reopen this issue if the problem persists.
