### ISSUE TITLE
Authentication with Game Center in Unity

### ISSUE THREAD

**Issue by daviddaco1** [heroiclabs/nakama-unity#133]
Hi Heroic team, I’m trying to authenticate with game center on iOS from unity using Client.AuthenticateGameCenterAsync();
but there are data that I can’t find, I proceed to enumerate them
-publickeyurl
-salt
-timestamp
-signature

**Comment by lugehorsam** [comment]
@daviddaco1 have you looked at any of the GameCenter SDKs from Unity? They should return what you need.

**Comment by mofirouz** [comment]
This isn't a bug or an issue with the Unity SDK. For development help, please follow up and ask further questions on our forum. Thanks.
