### ISSUE TITLE
IOS 15 Crash

### ISSUE THREAD

**Issue by Ali1Abbas** [heroiclabs/nakama-unity#139]
Alright so now I turn to you, good game devs.

I have published and successfully Unity project. My problem during matchmaking is the opponent can not reach other players to make matchmaking   Any help would be greatly appreciated!

**Comment by novabyte** [comment]
@Ali1Abbas Based on the title of this issue you encounter an iOS 15 crash but based on the contents of your issue you refer to advice on how to use the matchmaking features. Please can you clarify the issue you encounter and provide more information. I will close this issue in the meantime, re-open it when you've gathered the information for us. Thanks 🙏
