### ISSUE TITLE
Could you please provide original C# code for nakama.DLL?

### ISSUE THREAD

**Issue by Bruce-Chan** [heroiclabs/nakama-unity#140]
We implemented a lot of new feature for the server-side code, it is easy to modify the API IDL by regenerating the PB. But on the client side, the response struct is defined in the nakama.DLL. That makes us feel hard to customize it.

For example, we would like to modify the ApiUser struct to support FriendInviteEdgeCount and FriendBlockEdgeCount instead of EdgeCount. Now, we cannot finish it on the client-side.

**Comment by lugehorsam** [comment]
Hey @Bruce-Chan it's unclear to me exactly what your workflow is, but I am assuming you are talking about adding custom `.proto` files for your RPCs. The solution isn't to modify the original nakama source code but instead to parse the bytes from the RPC response into your custom proto messages. Does this make sense?

**Comment by Bruce-Chan** [comment]
> Hey @Bruce-Chan it's unclear to me exactly what your workflow is, but I am assuming you are talking about adding custom `.proto` files for your RPC responses. The solution isn't to modify the original C# source code but instead to parse the bytes from the RPC response into your generated custom .proto structs. Does this make sense?

Thanks for your reply, we are actually not only adding custom RPC function, we also want to modify the prebuilt struct and API method from Nakama.

**Comment by Bruce-Chan** [comment]
![image](https://user-images.githubusercontent.com/15301758/190653602-6558e7c3-c10c-4a89-8257-960c018fd5b4.png)

**Comment by lugehorsam** [comment]
We definitely don't support extending the Nakama API this way. We'd rather encourage a layering approach on top of the existing APIs as well as using our RPCs.

**Comment by Bruce-Chan** [comment]
![image](https://user-images.githubusercontent.com/15301758/190654058-c0b5d8da-cd2a-45a4-98c6-f8c27ea4faf5.png)

**Comment by Bruce-Chan** [comment]
> We definitely don't support extending the Nakama API this way. We'd rather encourage a layering approach on top of the existing APIs as well as using our RPCs.

But if we just use the custom RPC. We need to defined a lot of struct again on the client side, e.g. the User Struct, match struct, Party struct,  etc...

**Comment by lugehorsam** [comment]
Are you talking about redefining the structs provided by the Nakama SDK in order to parse RPC responses? Why would the former necessitate the latter?

**Comment by lugehorsam** [comment]
By the way, the original source code is in our .NET library: https://github.com/heroiclabs/nakama-dotnet

**Comment by Bruce-Chan** [comment]
A lot of work doesn't support for RPC. For example, we feel hard to support mobile phone message auth, because this framework assumes all the users have already login.

**Comment by Bruce-Chan** [comment]
> By the way, the original source code is in our .NET library: https://github.com/heroiclabs/nakama-dotnet

That is exactly what I want! Thanks a lot!!!

**Comment by lugehorsam** [comment]
It's still pretty unclear to me why you need to take this approach, so be careful, but that's where it lives 😄

**Comment by lugehorsam** [comment]
Hey @Bruce-Chan  could you actually either file an issue on Nakama or reach out to support so we could have a further dialogue about this? We want to further understand what you’re trying to do and potentially integrate some of your needs into Nakama. Otherwise you won’t be able to run on Heroic Cloud or use Nakama Enterprise.
