### ISSUE TITLE
Dont get data of leaderboard

### ISSUE THREAD

**Issue by Mehrdadgame** [heroiclabs/nakama-unity#145]
Hi
I have problem in get leader-board data in client (unity)
my problem is get data leader-board of local host but i do set port and host is VPS
I did create leader-board in server and save record in  leader-board console but didn't  get in unity 
log get leader board :
Send: method='GET', uri='http://127.0.0.1:7350/v2/leaderboard/b7c182b36*****?limit=1&', body=''

![Capture](https://user-images.githubusercontent.com/72225846/194855557-e6ceb53d-d715-4361-ac63-f758e099dd2e.PNG)

**Comment by lugehorsam** [comment]
@Mehrdadgame can you share what error you get and confirm that the leaderboards display in the console/

**Comment by lugehorsam** [comment]
@Mehrdadgame also can you wrap your call in a `try..catch` block?

**Comment by Mehrdadgame** [comment]
Hi Lugehorsam

![Capture1](https://user-images.githubusercontent.com/72225846/194863695-ed123f0b-a564-4b7b-bdc1-ae56403b87c0.PNG)

![Capture](https://user-images.githubusercontent.com/72225846/194863794-845a3ac7-805c-4abc-9fae-4d3f4cf45794.PNG)

**Comment by lugehorsam** [comment]
@Mehrdadgame it looks like an issue specific to your VPS. I would check your configuration settings. Are you able to authenticate properly? i.e., is this just a leaderboard issue?

**Comment by Mehrdadgame** [comment]
I did set NakamaConnectionData to VPS but  you see get leaderboard of local

**Comment by Mehrdadgame** [comment]
yes just a leaderboard issue

**Comment by Mehrdadgame** [comment]
now play to other players is good and send rpc and connecting with server is good

**Comment by Mehrdadgame** [comment]
@lugehorsam 
Now test VPS but get data leraderboard of localhost
I dont now why get data leaderboard of local host
Because Auth and game-play is connecting to VPS
