### ISSUE TITLE
Imatch Presences is empty 

### ISSUE THREAD

**Issue by peyman1959** [heroiclabs/nakama-unity#156]
There are 2 player in a match, I cache the Imatch that was returned by the socket.JoinMatchAsync, but one of my clients' match.Presences is empty for no reason! Is there any server-side or client-side permissions that I'm missing?

**Comment by lugehorsam** [comment]
Hey @peyman1959 -- the first client that joins will be joining an empty matches which is why `Presences` is empty. You should listen to `ISocket.ReceivedMatchPresence` for the second client who joins and then call `IMatch.UpdatePresences` on your match to keep the local copy up to date.
