### ISSUE TITLE
Connect to database

### ISSUE THREAD

**Issue by Mehrdadgame** [heroiclabs/nakama-unity#159]
Hi 
I have issue for connect database to Nakama.
I want to create game that requires a  database because , I need players to be able to download some files.
Is there a way to do this with storage or can i upload the data I want each user to download to an SQL database?

**Comment by mofirouz** [comment]
This isn’t an issue. Please put your questions on the forum: https://forum.heroiclabs.com

**Comment by Mehrdadgame** [comment]
Hi @mofirouz 
I have issue to connect Postgres . I did create Postgres db when connect in Pgadmin had a error password :my docker compos is 


`
version: '3.3'
services:
  postgres:
    container_name: postgres
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=12c45urg
      - POSTGRES_USER=postgres      
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "nakama"]
      interval: 3s
      timeout: 3s
      retries: 5

  nakama:
    container_name: PersainSong
    image: registry.heroiclabs.com/heroiclabs/nakama:3.13.1
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama &&
          exec /nakama/nakama --name SongPersian --database.address postgres:localdb@postgres:5432/nakama --logger.level DEBUG --session.token_expiry_sec 7200 --runtime.env "JWT_SECRET_KEY=2SoPDHoqJvSId__63qgzpKEPqgnEJCl_jayxdGt1mOo"

    restart: "always"
    depends_on:
      - postgres
    volumes:
      - ./:/nakama/data
    expose:
      - "7349"
      - "7350"
      - "7351"
      - "9100"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
`
