### ISSUE TITLE
Use database and redis

### ISSUE THREAD

**Issue by Mehrdadgame** [heroiclabs/nakama-unity#160]
I want to create a game with a database that contains various download links for songs. Each player downloads a song, plays it, and earns a score. However, we want to have a leaderboard for each song. I was thinking of doing this with Redis. Is there a solution to achieve this without using Redis because there are many songs? Another point is that I have a database containing the songs. How can I transfer them to the game database?"

@mofirouz

**Comment by lugehorsam** [comment]
Hi @Mehrdadgame  this is not a technical issue with the Nakama Unity SDK. Please take this question to our forums: https://forum.heroiclabs.com/

**Comment by Mehrdadgame** [comment]
https://forum.heroiclabs.com/t/use-database/4367
