### ISSUE TITLE
The document on the official website has not been updated  

### ISSUE THREAD

**Issue by w772007846** [heroiclabs/nakama-unity#161]
public class HatsStorageObject
{
    public string[] Hats;
}

**var readObjectId = new StorageObjectId
{
    Collection = "Unlocks",
    Key = "Hats",
    UserId = session.UserId
};

var result = await client.ReadStorageObjectsAsync(session, readObjectId);**

if (result.Objects.Any())
{
    var storageObject = result.Objects.First();
    var unlockedHats = JsonParser.FromJson<HatsStorageObject>(storageObject.Value);
    Debug.LogFormat("Unlocked hats: {0}", string.Join(",", unlockedHats.Hats));
}

**Comment by novabyte** [comment]
Thanks for the report. @heroiclabs/devrel can you take a look and update the docs? 🙏

**Comment by tomglenn** [comment]
@w772007846 Please can you let me know what the specific issue is here and we will look into getting it resolved. Thanks.

**Comment by tomglenn** [comment]
I'm going to close this issue as I'm unable to determine what change is being proposed here. @w772007846 if you feel this is a mistake please create a new issue with a detailed explanation of the problem and what you think should be fixed.
