### ISSUE TITLE
C# / Unity - [BUG] Client does not get return from server API call

### ISSUE THREAD

**Issue by Deity** [heroiclabs/nakama-unity#162]
Running with Unity `2022.3.11f1 Silison LTS` on a M1 Mac and connecting to Nakama server `3.18.0+095c7a66`, the code

`await NakamaManager.Instance.Client.UpdateAccountAsync(NakamaManager.Instance.Session, null, displayName);`

(as seen in [Ninja Battle Tutorial](https://heroiclabs.com/docs/nakama/tutorials/unity/ninja-battle/#setting-up-usernames) )
would not return control for Nakama Unity SDK version `3.8.0`or `3.9.0`.  The highest version number that appears to work is `v3.7.0`

**Comment by novabyte** [comment]
@Deity Thanks for the bug report. Do you have more information you can share with us which could help identify the root cause of the issue? We have a lot of game projects in production which use `UpdateAccountAsync` on Unity version 2022.3.11f1.

**Comment by novabyte** [comment]
We've not had any follow up since the original request for more information. @Deity Please re-open the issue if the issue persists.
