### ISSUE TITLE
[Ehancement] Open-Source Nakama.dll - Plugins

### ISSUE THREAD

**Issue by AleksandarEri** [heroiclabs/nakama-unity#163]
Would it be possible to open-source Nakama.dll Plugin that gets currently shipped within Unity?
Why?
I was investigating some things, mostly memory usage and working on ping=ing mecahnism to change while we are in game and not in game, and noticed under the hook nakama already creates PingPong manager that does the same thing o.O just it is protected and can't be hooked onto it...
So why to reinvent the wheel if Nakam.dll can be open sourced, so we could improve performances or hook onto already existing things :)
Thanks.

**Comment by mofirouz** [comment]
It is open-source: https://github.com/heroiclabs/nakama-dotnet
