### ISSUE TITLE
Trouble with Socket.AddMatchmakerAsync in Nakama

### ISSUE THREAD

**Issue by Its-Anonymous** [heroiclabs/nakama-unity#168]
**Socket.AddMatchmakerAsync(“*” , 2, 4);**

When using the **Socket.AddMatchmakerAsync** function with a **minCount of 2 and a maxCount of 4**, I’ve noticed that it behaves unexpectedly. Specifically, when three players request matchmaking, it only creates a match for two players. However, it works as expected when four players request matchmaking.

I’m curious to understand why this function seems to prioritize the minCount and maxCount exclusively, rather than accommodating an intermediate number of players between the specified range. If anyone has insights or suggestions on how to address this behaviour, I would greatly appreciate the assistance. Thank you!

**Comment by mofirouz** [comment]
This is not a client issue, you've also posted this in the forum already so the discussion can continue there:
https://forum.heroiclabs.com/t/trouble-with-socket-addmatchmakerasync-in-nakama/4955
