### ISSUE TITLE
MacOS support ?

### ISSUE THREAD

**Issue by samhvw8** [heroiclabs/nakama-unity#173]
Hi 

Thanks for your great work on the game server.

Is it possible to use the Nakama client with Unity on MacOS?

**Comment by lugehorsam** [comment]
Hey @samhvw8 yes it is. If you hit any specific issues let us know.

**Comment by samhvw8** [comment]
Hi @lugehorsam 
From our guide (https://heroiclabs.com/docs/nakama/client-libraries/unity/),  
it's require .Net 4.6 for using Nakama client, but i can not find .Net 4.6 for MacOS anywhere ? :(

**Comment by samhvw8** [comment]
Thank you !
