### ISSUE TITLE
Full documentation link is dead

### ISSUE THREAD

**Issue by wmcnamara** [heroiclabs/nakama-unity#175]
https://heroiclabs.com/docs/unity-client-guide

This link in the readme for the full docs is unfortunately a 404

**Comment by wmcnamara** [comment]
Should it be replaced with https://heroiclabs.com/docs/nakama/client-libraries/unity/ ?

**Comment by mofirouz** [comment]
Yes the new link is correct, we will provide redirecting aliases for the old link. Out of curiosity where did you see the old link?

**Comment by mofirouz** [comment]
Cc @heroiclabs/devrel to add alias please

**Comment by wmcnamara** [comment]
![image](https://github.com/heroiclabs/nakama-unity/assets/57050262/15310318-6c89-4204-a7f7-5de8c41bcc3c)

**Comment by wmcnamara** [comment]
I found it here

**Comment by mofirouz** [comment]
Thanks - the alias is now updated and the page should load.
