### ISSUE TITLE
Requesting a cleaner way to compare byte[] ID's

### ISSUE THREAD

**Issue by prodigga** [heroiclabs/nakama-unity#18]
I frequently need to compare the ID's of users/matches/etc when working with Nakama.

The ID's are byte[]'s, and you can't just compare them directly for equality to see if they are the same ID (myUser.ID == otherUser.ID only returns true if the references are the same, not if the byte[]'s are identical in content).

I've written my own utility method to compare each element in 2 byte[]'s for equality. 

This works fine for me, but since this is something almost everyone will need when working with Nakama, I feel like there should be a nicer way to compare the ID's built in to Nakama.

Can we store the ID's as 'long's instead of byte[]'s or something? Then comparison becomes simple.

**Comment by prodigga** [comment]
@JoshuaStrunk suggested created a NakamaID struct or class of some sort that wraps the byte[]. We could then just compare the objects `if(nakamaID1 == nakamaID2)`, use them as keys for dictionarys 

> Dictionary<NakamaID,SomeOtherType>

, etc.

**Comment by brinca** [comment]
I usually compare them as strings:

if (System.Text.Encoding.Default.GetString(Id) == System.Text.Encoding.Default.GetString(OtherId))
  Debug.Log("Match!");

Though this might be prone to errors...

**Comment by prodigga** [comment]
The issue isn't *how* to compare byte arrays, but that there isn't really a nice simple and quick way to do it out of the box :) Your example is fine, though it generate a lot of garbage and that could be a problem is code that is run, say, every frame. I just have a static helper method that takes 2 byte [] and compares them element by element.

**Comment by prodigga** [comment]
We want to be able to:

- Compare them
- Use them as keys for dictionaries
- Store them in Hashsets to see if we an incoming ID is within the set already.

Very common use cases, ones I've come across a lot personally, but none of them are possible "out of the box" with a byte[]

**Comment by Amir-LooLoo** [comment]
also you can use this extension method
`public static bool ByteArrayCompare(this byte[] a1, byte[] a2)
    {
        if (a1.Length != a2.Length)
            return false;

        for (int i = 0; i < a1.Length; i++)
            if (a1[i] != a2[i])
                return false;

        return true;
    }`
or convert them to a hex string and compare strings
`public static string ByteArrayToString(this byte[] ba)
    {
        string hex = System.BitConverter.ToString(ba);
        return hex.Replace("-", "");
    }

    public static byte[] StringToByteArray(this string hex)
    {
        int NumberChars = hex.Length;
        byte[] bytes = new byte[NumberChars / 2];
        for (int i = 0; i < NumberChars; i += 2)
            bytes[i / 2] = System.Convert.ToByte(hex.Substring(i, 2), 16);
        return bytes;
    }`

**Comment by novabyte** [comment]
@prodigga @brinca @Amir-LooLoo I've opened a pull request to add methods you've requested. There's both a helper class called `NIds` and an extension method on the byte array value type. I've not created a custom type to represent IDs (for use in maps and lists) because it'd break the current API. I think the change is valuable but might as well be deferred until Unity 2017 is available. Lets move the discussion onto the pull request - https://github.com/heroiclabs/nakama-unity/pull/29

**Comment by novabyte** [comment]
I've added a helper class for this use case. This work is now on master at https://github.com/heroiclabs/nakama-unity/commit/9e087ad5cfd0ea25000973fe0295abc99e2ef9fb. If you have any questions drop into the [community channel](https://gitter.im/heroiclabs/nakama).
