### ISSUE TITLE
The client has a conflict with the Archimatix asset

### ISSUE THREAD

**Issue by novabyte** [heroiclabs/nakama-unity#19]
This was reported in the community channel.

There's an issue with `Properties` files in the Unity client which conflict with those in the Archimatix asset. This produces the error:

```
Attribute '<attributename>' cannot be applied multiple times
```

The current workaround is to manually delete the Properties files after the asset is imported.

**Comment by rodgalvao** [comment]
The class of errors is: 

Attribute '<attributename>' cannot be applied multiple times

Where <attributename> is metalanguage used here to describe each of the attributes that generated an error message.

It seems it will work with other assets that have a property file imported also. In this case was Archimatix's.

**Comment by novabyte** [comment]
The client has been redesigned. Please re-open if you encounter the issue.
