### ISSUE TITLE
Missing script after client import from the asset store

### ISSUE THREAD

**Issue by rodgalvao** [heroiclabs/nakama-unity#21]
After I imported the Unity Nakama client from the asset store there were these errors:

1. NakamaScriptObject was missing a script

which I supposed was DemoScene.cs, so I attached it and updated the references to the respective buttons. The problem now is:

2. The buttons don't have actions associated with them

**Comment by novabyte** [comment]
I've added instructions on how to setup one of the demo scenes https://github.com/heroiclabs/nakama-unity/commit/df3271bbd6ee018d040b5ea5999d3e4ed9c695ee. Thanks
