### ISSUE TITLE
MatchDataSend requests seem to be buffered and sent in 50ms (or so) intervals.

### ISSUE THREAD

**Issue by prodigga** [heroiclabs/nakama-unity#22]
Client A sends one message per 100ms to client B, client B receives a message every 100ms. (Expected)

Client A sends one message per 15ms to client B, client B receives a message every 50ms. (Problem?) Message come in "groups". 2-3 messages per 50ms, with nothing in between.

Potentially an issue with an incorrectly configured client? Enable TCP_NoDelay and see if it resolves the issue? (Suggested by @zyro)

**Comment by zyro** [comment]
This is solved by the `NClient.NoDelay` option available since 4df07dd7f11a934d39b3a28785f587452f3c4296.
