### ISSUE TITLE
Conflict on NUsersFetchMessage.Builder with params overload

### ISSUE THREAD

**Issue by brinca** [heroiclabs/nakama-unity#25]
## Description
If you try to create a NUsersFetchMessage using an empty builder (`var message = NUsersFetchMessage.Builder();`), so you can later iterate and `Add()` the user ids in say a foreach loop, the compiler issues the following error:

`The call is ambiguous between the following methods or properties: 'NUsersFetchMessage.Builder.Builder(params byte[])' and 'NUsersFetchMessage.Builder.Builder(params string[])'
`
## Workaround
An ugly workaround is to extract the first argument of the users array, feed it to the Builder method,  and then iterate the ids using a for loop, skipping the first element (`i = 1`).
If anyone knows a better workaround please let me know.

## Environment
* **Custom build from latest (ab453fcf9652bb476827e8ad5c60c8fa7cbae1db) nakama-unity/master**
* Unity 5.6.1f1
* MacOS Sierra 10.12.5

**Comment by mofirouz** [comment]
This is fixed in #26 and will be in 0.6.1 release.
