### ISSUE TITLE
NullReferenceException when using NLeaderBoarRecordsListMessage.FilterByOwnerIds()

### ISSUE THREAD

**Issue by brinca** [heroiclabs/nakama-unity#27]
## Description
When filtering the leaderboards records with a list of user ids, by using the `FilterByOwnerId()` call, a NullReferenceException is thrown with the following (abridged) trace:
`NullReferenceException: Object reference not set to an instance of an object
Nakama.NLeaderboardRecordsListMessage+Builder.FilterByOwnerIds (IList'1 ownerIds) (at Assets/Extensions/Nakama/Plugins/Nakama/NLeaderboardRecordsListMessage.cs:79)
`

## Workaround
This is caused when trying to access `message.payload.LeaderboardRecordsList.OwnerIds.OwnerIds` because `message.payload.LeaderboardRecordsList.OwnerIds` is actually null.
My ugly workaround is to prepend the loop (at NLeaderboardRecordsListMessage.cs:76) with a `message.payload.LeaderboardRecordsList.OwnerIds = new TLeaderboardRecordsList.Types.Owners();` which seems to take care of the problem with no (visible) side effects.
If anyone knows a better workaround please let me know.

## Environment
* **Custom build from latest (ab453fcf9652bb476827e8ad5c60c8fa7cbae1db) nakama-unity/master** (but also present in the previous release)
* Unity 5.6.1f1
* MacOS Sierra 10.12.5

**Comment by mofirouz** [comment]
This is fixed in #26 and will be in 0.6.1 release.
