### ISSUE TITLE
Should we have simple demo for unity game

### ISSUE THREAD

**Issue by takaaptech** [heroiclabs/nakama-unity#38]
Hi,
I found it is awesome client - server support for Unity.
But it is still lack of document and demo. Would you please add some demo for the simple game, so we can study idea how to build a real game from it!
Thank so much!

**Comment by novabyte** [comment]
Hey @takaaptech you're right we need to build out some demo projects to make it easier to onboard developers. I've got plans to add code docs to the Unity client source files which should help with API discovery and am currently in the middle of a full rewrite and enhancement to our [main documentation](https://heroiclabs.com/docs).

In the meantime I recommend you join our [community channel](https://gitter.im/heroiclabs/nakama) and we can help you get started; also have a look at the code examples in the [repo](https://github.com/heroiclabs/nakama-unity/tree/cdm-unitythread-dispatch/example).

**Comment by takaaptech** [comment]
Thank so much @novabyte!
