### ISSUE TITLE
Assembly BCCrypto could not be found error.

### ISSUE THREAD

**Issue by luochuanyuewu** [heroiclabs/nakama-unity#47]
ArgumentException: The Assembly BCCrypto is referenced by Netcode.IO.NET ('Assets/Nakama/Plugins/Netcode.IO.NET.dll'). But the dll is not allowed to be included or could not be found.
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1 alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2 cache, BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:152)
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1 alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2 cache, BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:158)
UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:192)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()

**Comment by zyro** [comment]
There was a packaging issue with version 0.10.0 of the client that caused this issue with one of the bundled dependencies. It was fixed in version 0.10.1.

@luochuanyuewu Can you double-check you're using the latest version of the Unity client, otherwise if upgrading fixes the issue?
