### ISSUE TITLE
WebGL does not compile.

### ISSUE THREAD

**Issue by AlexVK79** [heroiclabs/nakama-unity#48]
I guess WebGL worked some time ago, but the most recent Asset Store version dpes not compile
because NTransportJavascript does not implement these (new?) methods:

        void SetOnClose(Action<SocketCloseEventArgs> OnClose);
        void SetOnError(Action<SocketErrorEventArgs> OnError);
        void SetOnMessage(Action<SocketMessageEventArgs> OnMessage);
        void SetOnOpen(Action OnOpen);

**Comment by zyro** [comment]
Looks like this is a regression introduced when we changed some of the internals of the client in 0.10.0. I'll start the ball rolling on a patch and an updated release.

As soon as I have the changes ready I'll get back to you here so you can at least update the sources in your project and carry on until the updated client package goes through the Unity Asset Store submission process.

**Comment by zyro** [comment]
@AlexVK79 It's still going through our test cycle but try replacing your `NTransportJavascript.cs` with [the updated version](https://raw.githubusercontent.com/heroiclabs/nakama-unity/67e7e80226d448a8e555d1a2516f5c22f694f947/Nakama/NTransportJavascript.cs).

**Comment by AlexVK79** [comment]
Thanks! It seems to compile now and connects to server. I didn't have a chnce to test any further, but it looks good so far.

**Comment by zyro** [comment]
The fix is part of the latest [0.10.2 release](https://github.com/heroiclabs/nakama-unity/releases/tag/v0.10.2).
