### ISSUE TITLE
Unity WebGL ReferenceError: Can't find variable: callback Object

### ISSUE THREAD

**Issue by igavva** [heroiclabs/nakama-unity#51]
Hi. When i build my test project in Unity WebGL error: ReferenceError: Can't find variable: callback Object. Nakama is support Unity WebGL?

My test script:

using UnityEngine;
using Nakama;
using System;

public class ServerTest : MonoBehaviour
{
    INClient client;
    INSession session;

    void Start()
    {
        client = new NClient.Builder("defaultkey")
        .Host("127.0.0.1")
        .Port(7350)
        .SSL(false)
        .Build();

        string id = SystemInfo.deviceUniqueIdentifier;
        var request = NAuthenticateMessage.Device(id);
        client.Login(request, (INSession session) =>
        {
            Debug.Log("Player Logged in successfully");
            this.session = session;

        }, (INError error) =>
        {
            Debug.LogErrorFormat("ID login '{0}' failed: {1}", id, error);

            if (error.Code == ErrorCode.UserNotFound)
            {
                client.Register(request, (INSession session) =>
                {
                    Debug.Log("Player Register in successfully");
                    this.session = session;

                }, (INError err) =>
                {
					Debug.LogErrorFormat("ID login '{0}' failed: {1}", id, err);

                });
            }
        });
    }
}

**Comment by novabyte** [comment]
@igavva Hmmm. I checked our WebGL build last week. What version of Unity do you use?

**Comment by igavva** [comment]
My Unity vession is 2017.2.0f3 Mac OS

**Comment by novabyte** [comment]
@igavva I'll run some checks and report back

**Comment by novabyte** [comment]
@igavva This works with Unity 2017.1.1p4:

```csharp
using Nakama;
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class WebGLTester : MonoBehaviour {

    private static readonly Action<INError> ErrorHandler = err =>
    {
        Debug.LogErrorFormat("Error: code '{0}' with '{1}'.", err.Code, err.Message);
    };

    private INClient _client;

    private void Start() {
        _client = NClient.Default("defaultkey");

        Action<INSession> sessionHandler = session =>
        {
            Debug.LogFormat("Session: '{0}'.", session.Token);
            _client.Connect(session, done =>
            {
                Debug.Log("Server connected.");
            });
        };

        var deviceid = "998c7f46-d78a-11e7-90fd-37965f77ee64";
        var message = NAuthenticateMessage.Device(deviceid);
        _client.Login(message, sessionHandler, err =>
        {
            if (err.Code == ErrorCode.UserNotFound)
            {
                _client.Register(message, sessionHandler, ErrorHandler);
            }
            else
            {
                ErrorHandler(err);
            }
        });
    }

    private void Update() {
    }

    private void OnApplicationQuit() {
        _client.Disconnect();
    }

}
```

You'll need to change this to another login method:

```
var deviceid = "998c7f46-d78a-11e7-90fd-37965f77ee64";
// SystemInfo.deviceUniqueIdentifier does not work in WebGL builds with Nakama server.
// It generates IDs which are not unique enough.
```

I recommend you look at our email/password login option or similar for a WebGL game. Please try the script and let me know if I can close this issue.

**Comment by igavva** [comment]
Ok. Thanks!
