### ISSUE TITLE
Unity Example UserChat not work

### ISSUE THREAD

**Issue by igavva** [heroiclabs/nakama-unity#52]
Unity - http://clip2net.com/s/3Q0doLT
Nakana - http://c2n.me/3Q0dYbg.png
Nakana config - http://c2n.me/3Q0ech4.png
Cockroach - http://c2n.me/3Q0e0bi.png

Steps1: Regester User1 or 2 - OK
Steps2: Login User1 or 2 -OK
Step3: Join TM Topic - Invalid user Id

Nakana - no massage in console
Cockroach - no job

**Comment by zyro** [comment]
@igavva Looks like you're using a very outdated version of Nakama. Make sure you update to the latest release ([1.3.0 right now](https://github.com/heroiclabs/nakama/releases/tag/v1.3.0)) and try again.

Did you install Nakama through Homebrew? I think that's not up to date, I'll make a note to fix that.

**Comment by igavva** [comment]
Yes. I Install nakama with brew ) Version 0.13.0 I update to 1.3.0 fixing my problem. Thanks!
