### ISSUE TITLE
Null Reference

### ISSUE THREAD

**Issue by ArisTsevrenis** [heroiclabs/nakama-unity#55]
Running as UDP, got this null reference error when sending data. It was done whilst sending data as normal in the editor

NullReferenceException: Object reference not set to an instance of an object
ReliableNetcode.ReliableMessageChannel.SendMessage (System.Byte[] buffer, Int32 bufferLength)
ReliableNetcode.ReliableEndpoint.SendMessage (System.Byte[] buffer, Int32 bufferLength, QosType qos)
Nakama.NTransportUdp.SendAsync (System.Byte[] data, Boolean reliable, System.Action`1 completed) (at Assets/Scripts/Nakama/Plugins/Nakama/NTransportUdp.cs:346)
Nakama.NClient.Send (INUncollatedMessage message, Boolean reliable, System.Action`1 callback, System.Action`1 errback) (at Assets/Scripts/Nakama/Plugins/Nakama/NClient.cs:253)
Nakama.NClient.Send (INUncollatedMessage message, System.Action`1 callback, System.Action`1 errback) (at Assets/Scripts/Nakama/Plugins/Nakama/NClient.cs:268)

**Comment by novabyte** [comment]
I'll triage this issue. Please re-open if you can reproduce on the latest client SDK. Thanks!
