### ISSUE TITLE
Stops receiving data after roughly 260 times

### ISSUE THREAD

**Issue by ArisTsevrenis** [heroiclabs/nakama-unity#56]
Not sure if this should be in Unity or Nakama issues

It happens consistently around the 250-260th time when receiving data in a match:
private void OnClientOnMatchData( INMatchData matchData ) both in UDP and WebSocket
it stops getting a call back even though the other user keeps sending data successfully. 

I currently tried to send a lot of concurrent data by sending every frame but it also happens if I send it once every 30+ frames

**Comment by ArisTsevrenis** [comment]
With websocket it happens a lot more rarely and with a lot more messages.

**Comment by prodigga** [comment]
@mofirouz  this is the issue I was referring to re RUDP issues not being resolved, just to be clear.
