### ISSUE TITLE
Architecture doesn't support dynamic Write

### ISSUE THREAD

**Issue by ArisTsevrenis** [heroiclabs/nakama-unity#57]
I might misunderstanding something but if I wanted to dynamically create the .Write  I wouldn't be able to with the current architecture as I always need to hardcode the number of things to write.

`NStorageWriteMessage message = new NStorageWriteMessage.Builder()
            .Write( bucket, "saves", "savegame", saveGame )
            .Write( bucket, "stats", "mystats", myStats )
            .Build();`

**Comment by novabyte** [comment]
@ArisTsevrenis I think you have some confusion. What exactly is a "dynamic write"? The code above shows how you write a storage object as a record into a collection within a bucket. This is the same as how every database works. You specify the namespace you want the data to live within. What behaviour would you expect?

**Comment by novabyte** [comment]
After a discussion on the community channel a code example shows how this would work:

```csharp
var writeBuilder = new NStorageWriteMessage.Builder();
writeBuilder.Write(bucket, "saves", "savegame", saveGame);
writeBuilder.Write(bucket, "stats", "mystats", myStats);
var message = writeBuilder.Build();
```
