### ISSUE TITLE
WebGL can't connect to nakama 

### ISSUE THREAD

**Issue by RomanZhu** [heroiclabs/nakama-unity#59]
If we call anything to connect to nakama in WebGL we will get an error

For example if we call (same with other auths) :
```
 var message = NAuthenticateMessage.Facebook(oauthToken);
client.Login(message, (session)
```

We will get:
```
writeStringToMemory is deprecated and should not be called! Use stringToUTF8() instead! 
InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.,Error: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
```

Unity 2017.2.0f3 All browsers

**Comment by RomanZhu** [comment]
Looks like it's problem with our nakama/nginx configuration

**Comment by j2l** [comment]
+1
I have the same problem and I use the docker image. 
What did you change?
Thanks
