### ISSUE TITLE
Dokumentation PDF Error Page 9

### ISSUE THREAD

**Issue by BernhardRubow** [heroiclabs/nakama-unity#62]
Error in the passage

Fetch Self
The client can retrieve the currently logged-in user data from Nakama. This data includes common
fields such as handle, fullname, avatar URL and timezone. Self will also include user’s login
information such as a list of device IDs associated and their social IDs.
``` csharp
var message = NSelfFetchMessage.Default();
client.Send(message, (INSelf self) => {
    Debug.LogFormat ("The user's ID is '{0}'.", self.Id);
    Debug.LogFormat ("The user's fullname is '{0}'.", self.Fullname); // may be null
    Debug.LogFormat ("The user's handle is '{0}'.", user.Handle);
}, (INError error) =>
{
    Debug.LogErrorFormat ("Could not retrieve self: '{0}'.", error.Message);
});
```

user.Handle should be self.Handle.

**Comment by novabyte** [comment]
The documentation has now changed with the latest release which is compatible with Nakama 2. Thanks
