### ISSUE TITLE
Additional parameter in Unity client

### ISSUE THREAD

**Issue by parmaia** [heroiclabs/nakama-unity#64]
In authentication methods like `Client.AuthenticateEmailAsync()`, the parameters _create_ or _username_ are not exposed.

This also happens in all the `Client.Authenticate*Async()` methods. 

There are other methods in `Client` that don't expose all the available parameters, for example `Client.CreateGroupAsync()`...

**Comment by novabyte** [comment]
@parmaia This is resolved in https://github.com/heroiclabs/nakama-dotnet/commit/c617e02d5ae8e045c355506ffacf4b007fc252d2 and will be part of the next release.

**Comment by parmaia** [comment]
Excellent! Thanks.
