### ISSUE TITLE
nk.register_req_after issue

### ISSUE THREAD

**Issue by Brianelvio** [heroiclabs/nakama-unity#66]
Hi,

I'm not sure if I am doing something wrong or what but I made a registration module based on the init user documentation in the tutorial section.

Am I correct to assume that this line here:
`nk.register_req_after(initialize_user, "AuthenticateDevice")`

Fires the initialize_user function as soon as the server recieves a client that authenticates with deviceid?

Because it is not doing that at this moment and my head is hurting as to why it won't.

**Comment by mofirouz** [comment]
@Brianelvio You've hit a known issue that's already fixed in master. It will be in Nakama 2.1 scheduled for release next week. Apologies for the inconvenience.

**Comment by Brianelvio** [comment]
Awesome, thanks!
