### ISSUE TITLE
Nakama 2.x is no longer supported in WebGL (Potentially because of System.Threading in Nakama Dotnet)

### ISSUE THREAD

**Issue by 5un** [heroiclabs/nakama-unity#67]
Seems like Nakama 2.x no longer works in WebGL probably because of the use of System.Threading in [Nakama Dotnet](https://github.com/heroiclabs/nakama-dotnet)

Steps to Reproduce
1. Create a new Project in Unity (version 2018.2.12f1)
2. Go to Asset Store, get Nakama client (version 2.0.0), or get 2.1.0 release Unity package from Github 
3. Change the .NET version in the Unity project settings to 4.x
4. Restart Unity as required
5. Create a game object and add SimpleSocket script
6. Works fine in the Editor
7. Build and run a WebGL build and get SystemException: Thread creation failed

Full error (Chrome 71)
UnityLoader.js:4 SystemException: Thread creation failed.
UnityLoader.js:4   at System.Threading.Thread.StartInternal (System.Security.Principal.IPrincipal principal, System.Threading.StackCrawlMark& stackMark) [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:4 Rethrow as TypeInitializationException: The type initializer for 'System.Threading.Timer.Scheduler' threw an exception.
UnityLoader.js:4 
UnityLoader.js:4 Rethrow as TypeInitializationException: The type initializer for 'System.Threading.Timer' threw an exception.
UnityLoader.js:4   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:4 --- End of stack trace from previous location where exception was thrown ---
UnityLoader.js:4   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:4 --- End of stack trace from previous location where exception was thrown ---
UnityLoader.js:4   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:4 --- End of stack trace from previous location where exception was thrown ---
UnityLoader.js:4   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <00000000000000000000000000000000>:0 
UnityLoader.js:4  
UnityLoader.js:4 (Filename: currently not available on il2cpp Line: -1)
UnityLoader.js:4 
blob:http://localhost:59767/91a41be4-4741-4ab2-a4f8-ddac4b001d76:2 warning: 2 FS.syncfs operations in flight at once, probably just doing extra work

Is there any plan to support this? Or should I look into creating a fork of Nakama Dotnet. Thanks so much!

**Comment by novabyte** [comment]
Hi @5un. You’re right we don’t have compatibility with WebGL exports in the client right now. It’s not too difficult to do but I’m curious why you need it? 

It’s difficult for us to gauge how many studios make use of WebGL and Unity given the history of serious performance problems with it.

**Comment by 5un** [comment]
We are seriously considering WebGL for distribution purposes, and yes, performance in Unity WebGL builds is such a headache. Thanks so much for the clarification!

**Comment by 5un** [comment]
@novabyte Thanks for pointing me to the transport class! I think I might take a stab at building WebGL support. 

However, I was a bit confused when you mentioned that it was not too difficult to do. Do you mean patching nakama-dotnet to support WebGL builds or making the 0.x/1.x Unity clients to support 2.x protocol? I thought there's already a WebSocket transport in nakama-dotnet. Would be great if you could point out the easiest way to go about this. Thanks a lot!

**Comment by igavva** [comment]
Hi. We are also interested in supporting Nakama 2 Webgl.  My error - https://c2n.me/3Xrtf6m.png

**Comment by Moriel12** [comment]
We also have the problem on our side.  And if we look quickly at the code of the client, the client is not close from being compatible with WebGL Unity builds.  Also, the asm.code.unityweb generated grows by more than 2MB when including the client + the .Net 4.x switch (about 1MB each), which really hurts when trying to limit the size of the app.

I think it should be documented that WebGL is not supported.

**Comment by novabyte** [comment]
@Moriel12 I have some ideas on how we can introduce support for WebGL within the client but we've had some trouble to justify the work because most games launch on mobile, desktop, or console with Unity and any that target the web really use a different game engine usually something JavaScript-based. Why did you choose Unity for a browser project?

**Comment by Moriel12** [comment]
@novabyte We chose Unity because we launch on mobile and browser.

**Comment by gupta-vaibhav** [comment]
@novabyte +1 for this request. We also intend to run our game on web along with mobile.

**Comment by novabyte** [comment]
Thanks @5un. This is fixed and will be part of the next client SDK.

**Comment by logixworx** [comment]
Can you also update the Jolly Roger Unity demo to work in WebGL? Thanks

**Comment by novabyte** [comment]
@logixworx Sure. Would you open the issue on the demo project repo?

**Comment by ssmasrour** [comment]
In the age of web3, WebGL support is a must. We failed a few sprints in one of our projects because we chose Nakama. 
It is a great tool, however it is not available on the web platform yet :(

**Comment by mofirouz** [comment]
Nakama 2.x is over 3 years old. Nakama 3.x has Unity WebGL support. Please upgrade. Locking this thread as no longer relevant.
