### ISSUE TITLE
stream.State is null

### ISSUE THREAD

**Issue by gupta-vaibhav** [heroiclabs/nakama-unity#68]
Hi, this is with reference to the discussion we had on gitter, we are opening an issue for this.. We tried to read the message on a stream, the message was received but the state was null. Here are the details with sample code:

#Server Code
We subscribed a user to a stream through Lua code on server as follows:

```
local stream_id = { mode = 123, label = "my custom stream", subject = context.user_id }
local hidden = true
local persistence = false
nk.stream_user_join(context.user_id, context.session_id, stream_id, hidden, persistence)
```

Then we sent a message on this stream for the user:
```
local stream_id = { mode = 123, label = "my custom stream", subject = context.user_id }
local payload = nk.json_encode({ some = "Data" })
nk.stream_send(stream_id, payload)
```

#Client code
On Unity, we wrote the following code to process the message:
```
_socket.OnStreamState += _socket_OnStreamState; 
```

To receive message and inside
```
_socket_OnStreamState() {
    Debug.Log( (stream.State == null));
} 
```

This printed true, confirming that the stream.State received was null. Do let us know in case you need more info / logs / code on this.

Best,

**Comment by novabyte** [comment]
@gupta-vaibhav do you have debug level logs output of the stream responses sent by the server?

**Comment by gupta-vaibhav** [comment]
Chris, there were no debug level logs that printed for this. Here is the code that I used:

```
    local stream_id = { mode = 123, label = "my custom stream", subject = context.user_id }
    local hidden = true
    local persistence = false
    print('----registering for stream---')
    nk.stream_user_join(context.user_id, context.session_id, stream_id, hidden, persistence)
    print('----registered for stream---')
```

And here is the code that I used for sending the data on stream:
```
    print('----Sending data on stream---')
    local stream_id = { mode = 123, label = "my custom stream", subject = context.user_id }
    local payload = nk.json_encode({ some = "Data" })
    nk.stream_send(stream_id, payload)
    print('----Sent data on stream---')
```

Here are the logs from the server, nothing printed here:
```
----registering for stream---
----registered for stream---
----Sending data on stream---
----Sent data on stream---
```

The server was running in debug mode as it was started with " --logger.level DEBUG" option and we could see other debug level logs such as:
```
{"level":"debug","ts":"2018-11-26T15:07:16.708+0530","msg":"Sending *rtapi.Envelope_Rpc message","uid":"ce9e3ea6-fff8-4a40-8ac6-e4444b9c5842","sid":"6aeaa02f-63ce-4f4e-8b80-168fbdfadeb8","payload":"{\"cid\":\"676487a7-f44a-4086-9e77-614911a6cd3e\",\"rpc\":{\"id\":\"logininfo\",\"payload\":\"{\\\"activematch\\\":\\\"none\\\"}\"}}"}
```

Is there anything else that I need to do in order to print more detailed debug logs?

**Comment by zyro** [comment]
@gupta-vaibhav One of the debug messages should have `"msg":"Sending *rtapi.Envelope_StreamData message"` or similar. Can you share the full log line that matches?

**Comment by gupta-vaibhav** [comment]
@zyro I have verified a few times but there is no such log as ```"msg":"Sending *rtapi.Envelope_StreamData message"``` 

I can also confirm that the server is running in debug mode, since I am getting debug logs, such as:
```
{"level":"debug","ts":"2018-11-28T11:42:16.815+0530","msg":"Sending *rtapi.Envelope_Rpc message","uid":"75395e64-ad0c-47b6-8f9c-02963d94acef","sid":"472aef9f-f357-4269-882e-a524ac711d00","payload":"{\"cid\":\"037b53e5-0daa-4e5e-b28e-88364f5a6dfa\",\"rpc\":{\"id\":\"logininfo\",\"payload\":\"{\\\"activematch\\\":\\\"none\\\"}\"}}"}
```

Despite no debug logs on server for StreamData, we are getting the logs on Unity with mode, label and subject, but no State. State was null. Let me know what else can I do to help debug this.

**Comment by clw123456** [comment]
I had same problem

**Comment by novabyte** [comment]
This is fixed and will be part of the next release of the client SDK.
