### ISSUE TITLE
Nakama.Client missing definitions

### ISSUE THREAD

**Issue by fighder** [heroiclabs/nakama-unity#69]
I just imported a fresh package from the asset store, as well as the releases, and both seem to be missing a lot of references in the Nakama.Client class.

The following image shows everything that is missing.
![capture](https://user-images.githubusercontent.com/16496395/52577550-54d29a80-2df0-11e9-920e-4ddbcba1559d.PNG)

**Comment by mofirouz** [comment]
From the looks of the code you've pasted, you are using a very old client library that is compatible with Nakama 1.x. Can you show some of your code and where you download the the Asset from?

**Comment by fighder** [comment]
I deleted the Nakama folder again just now and imported the package from the release page here instead of the Asset Store, the missing definitions seem to be resolved. I noticed the package on the release page is later than the one in the Asset store.

I didn't delete the folder when I imported from the release the page first time, guess that was the problem.

**Comment by mofirouz** [comment]
Glad that's resolved. 👍
