### ISSUE TITLE
Socket immediately disconnects

### ISSUE THREAD

**Issue by aaronjamt** [heroiclabs/nakama-unity#72]
First, I want to say that Nakama is awesome! Thanks to the brilliant team who made it!

My issue is this: I run the following code, which seems to work at first, but about 2-5 seconds after I get a "Socket Connected" message, I get a "Socket Disconnected" message.
account.cs:

        socket = client.CreateWebSocket();
        multiplayer.SetupCallbacks();

        await socket.ConnectAsync(session);
        multiplayer.Join();

multiplayer.cs (SetupCallbacks):

        account.socket.OnConnect += (sender, evt) => Debug.LogFormat("Socket connected");
        account.socket.OnDisconnect += (sender, evt) => Debug.LogFormat("Socket disconnected");
        
multiplayer.cs (Join):

        match = await account.socket.CreateMatchAsync();

I'm not sure where the issue could be, if anyone needs more code I will gladly post it here. Thanks in advance!

**Comment by novabyte** [comment]
Thanks for the kind words @aaronjamt. We'll need more info to help understand what causes the socket to disconnect. My guess is that there's some code of yours that blocks the socket thread. Do you think that could be possible? Maybe a semaphore somewhere?

**Comment by aaronjamt** [comment]
I think I figured it out. My code was Destroy()-ing a GameObject within the OnMatchPresence method, but I realized that Destroy() has to run on the main thread. I set it up to where the OnMatchPresence method adds the key to a List<string> and Destroy() the GO in the Update method. But thanks for the fast response anyways!

**Comment by novabyte** [comment]
Nice one @aaronjamt we usually recommend you use this project which helps with the execution of UnityEngine APIs on the Unity main thread: https://github.com/PimDeWitte/UnityMainThreadDispatcher
