### ISSUE TITLE
Server dispatcher.broadcast_message() with nil data will disconnect client socket and raises an Exception

### ISSUE THREAD

**Issue by fsufyan** [heroiclabs/nakama-unity#73]
Sending message from server using nil in data parameter:
`dispatcher.broadcast_message(101, nil, nil, nil)`
will cause Unity socket to disconnect and raises the following exception:
ArgumentNullException: Value cannot be null.
Parameter name: s
System.Convert.FromBase64String (System.String s) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
Nakama.MatchState.get_State () (at <5d5477e0de7d4f1abb47203789b43738>:0)

Please note that this exception is not catched unless you execute the OnMatchState event in Unity main thread!

The only workaround now is to pass empty string "" if you don't want to send any data
`dispatcher.broadcast_message(101, "", nil, nil)`

Server version: Nakama 2.5.1
Client version: Unity 2.1.0

**Comment by novabyte** [comment]
Thanks @fsufyan. This is fixed and will be part of the next release of the client SDK.
