### ISSUE TITLE
Unable to find libc

### ISSUE THREAD

**Issue by CamDHall** [heroiclabs/nakama-unity#74]
I'm running Unity 2019.1.6f1 and testing with a Pixel 3. On creating a new connection this scene freezes.
` Client client = new Client("http", "[addressofmyserver].com/", 7350, "defaultKey");`

When I run logcat I'm seeing this error: 
`Unable to find libc`

Then if I try to create a session it results in a null exception, as the client wasn't created due to the libc error. 

`NullReferenceException: Object reference not set to an instance of an object`

I've tried changing build settings and targets, but no improvements.

**Comment by novabyte** [comment]
@CamDHall Are you on Windows, macOS, or Linux?

It's possible you've run into this bug in Unity:

https://issuetracker.unity3d.com/issues/android-mono-il2cpp-unable-to-find-libc-error-thrown-when-executing-certain-sslstream-constructor

As an experiment can you try the constructor which uses `UnityWebRequest` adapter instead of the `HttpRequestAdapter`. i.e.

```csharp
var client = new Client("http", "[addressofmyserver].com", 7350, "defaultkey", UnityWebRequestAdapter.Instance);
```

**Comment by CamDHall** [comment]
This seems to solve the problem. Though I'm having an SSL issue now. I don't believe it's related, however, can you point me to recent documentation on using an SSL connection in Unity?

**Comment by novabyte** [comment]
@CamDHall It's not a problem in the Nakama client but a bug in Unity Engine.

What error do you get with SSL?

**Comment by CamDHall** [comment]
@novabyte yes sorry, to clarify I this libc issue is not a Nakama issue, but I wasn't able to find a solution to it, thank you for the help. 

As for the SSL, I'm certain I'm missing something simple. 

`javax.net.ssl.SSLHandshakeException: Handshake failed`
