### ISSUE TITLE
SSL Configuration Options Using docker compose

### ISSUE THREAD

**Issue by CamDHall** [heroiclabs/nakama-unity#76]
The compose file doesn't recognize the options for `socket` or `session` which seems to be required for setting up SSL.

**Comment by zyro** [comment]
@CamDHall Can you add more detail please? What exactly have you tried, and what error or behaviour do you see?

**Comment by CamDHall** [comment]
Placing this anywhere in a config file or docker compose:

`socket:
  server_key: "defaultkey"
  port: 7350
  max_message_size_bytes: 4096 # bytes
  read_timeout_ms: 10000
  write_timeout_ms: 10000
  idle_timeout_ms: 60000
  write_wait_ms: 5000
  pong_wait_ms: 10000
  ping_period_ms: 8000 # Must be less than pong_wait_ms
  outgoing_queue_size: 16

session:
  encryption_key: "defaultencryptionkey"
  token_expiry_sec: 60`

Causes an error on restart:
`socket not a valid option`. Or ``session not a valid option`

**Comment by zyro** [comment]
I see, you're trying to set Nakama config as part of the docker-compose file. That won't work, [docker-compose has a strict specification](https://docs.docker.com/compose/compose-file/) so you can't add random fields there.

You can see in the example docker-compose file how you should set options through [command-line arguments here](https://github.com/heroiclabs/nakama/blob/master/docker-compose.yml#L22).

Either way this is not a problem in the Unity client, so closing the issue now.

**Comment by CamDHall** [comment]
I've changed my docker-compose file to match what the documentation has. This works, but I still get a failed SSL handshake. Using SSL directly throws the same SSL handshake failure error.
