### ISSUE TITLE
400 Bad Request after custom Authenticate Custom Call

### ISSUE THREAD

**Issue by CamDHall** [heroiclabs/nakama-unity#77]
I'm using a custom ID that successfully creates a user. However, when I launch the game again, I get a 400 when I try to create a socket.

```
       session = await client.AuthenticateCustomAsync(custom_id);
        Debug.LogFormat("New user: {0}, {1}", session.Created, session);
        var socket = client.NewSocket();
        socket.Connected += () =>
        {
            Debug.Log("Connected");
            TestingUtils.SetMessage("Connected");
        };

        socket.Closed += () =>
        {
            TestingUtils.SetMessageAdditive("Closed");
        };

        await socket.ConnectAsync(session);
```

No other code is running, but I get:

`InvalidHttpResponseCodeException: 400 Bad Request`

It succeeds on creation, however.

**Comment by novabyte** [comment]
@CamDHall My guess is your game code logic caches the session token to avoid the `AuthenticateCustomAsync` call at each game start which is what we recommend. Have you looked at the session token expiry settings you're using?

By default the server uses just 60 seconds this is intended to remind developers to set a value which makes most sense for the game. Usually a good value is 3-4 times the expected average play session length of the game. Whatever value you expect that to be.

**Comment by CamDHall** [comment]
@novabyte I'm actually running this on Start. After our custom authentication is completed, I'm running

`session = await client.AuthenticateCustomAsync(custom_id);`

Our token expiry is set to 8 minutes regardless.

**Comment by CamDHall** [comment]
@novabyte I moved the AuthenticateCustomAsync into a separate project to test. I get the same 

`Bad Request` error. As well as `Unable to find Kernel32` which seems to be a windows error. But I'm running on an Android Device.

**Comment by mofirouz** [comment]
@CamDHall do you have any custom Lua/Go code as CustomAuth Before Hooks on the server?

**Comment by CamDHall** [comment]
@mofirouz

No. Nothing special. We're using EasyMobile to handle logins and achievements. I can try ripping that out and just hard coding an ID, but there's no Lua/Go in our codebase.

**Comment by CamDHall** [comment]
@mofirouz I pulled out our custom authentication code. I'm just calling 

```
var client = new Client("https", "our.url.com/", ourPort, key, UnityWebRequestAdapter.Instance);
var session = await client.AuthenticateCustomAsync("adfadsasdfasdf-asdfadsfasdf-asdfasdfasdf-asdfasdfa");
var socket = client.NewSocket();
```

Authentication works. But client.NewSocket() still throws the 400 Bad request.

**Comment by novabyte** [comment]
@CamDHall `client.NewSocket()` doesn't open a socket it just constructs a socket object. It would not throw a 400 bad request because it doesn't make a request. I think we should speak over the [community channel](https://gitter.im/heroiclabs/nakama) to debug it in realtime. I cannot reproduce it at all.

**Comment by CamDHall** [comment]
@novabyte to be clear, I have 


```
var socket = client.NewSocket();
Debug.LogFormat("New user: {0}, {1}", session.Created, session);
socket.Connected += () =>
{
     Debug.Log("Connected");
};

socket.Closed += () =>
{
    Debug.Log("Closed");
};

await socket.ConnectAsync(session);
```

It throws the bad request and then closes. So I'm not just creating a new socket and then getting a bad request. It's attempting a connection and throws a 400.

**Comment by Shelim** [comment]
I'm facing the same issue - my server is also behind Apache proxy and uses HTTPS. The end point /ws gives correctly "Missing or invalid token".

Any status on this?

**Comment by Shelim** [comment]
Okay, this looks like server issue - I intercepted a call that Nakama is doing on /ws and point and run in directly in browser. The result is still "Bad Request". I am not that good with debugging Go, but let me try it...

**Comment by Shelim** [comment]
There is very interesting warning in nakama server log:

`{"level":"warn","ts":"2019-11-07T10:27:49.573+0100","msg":"Could not upgrade to WebSocket","error":"websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"}`

Looks like it's something with Apache reverse proxy config...

**Comment by mofirouz** [comment]
This is definitely a misconfiguration on Apache, or whatever reverse proxy you are using. We have thousands of games using Nakama with various authentication mechanism, incl custom auth and we've not faced this issue.
