### ISSUE TITLE
CORS error when authenticating with wrong credentials (only on WebGL), behaves properly otherwise

### ISSUE THREAD

**Issue by andreyrk** [heroiclabs/nakama-unity#88]
CORS blocks XMLHttpRequest and throws ```No 'Access-Control-Allow-Origin' header is present on the requested resource.```. 

Happens only on WebGL and when trying to authenticate with invalid credentials (e.g what should throw invalid e-mail format, incorrect password or other useful logs, instead throws a CORS error and no information about what actually failed). 

Non-WebGL platforms throw proper ApiResponseException. PS: I assume this is not server-related as I use the same server for a Godot project. FWIW the WebGL version is hosted at: https://kag-rewritten.github.io/ (and code at respective repo) if you feel the description is not enough.

**Comment by novabyte** [comment]
Thanks for the report @andreyrk. I'll see what we can do to make sure the OPTIONS request succeeds even if the underlying HTTP request returns a non-200 status code.

**Comment by DreadKnight** [comment]
And now all of a sudden I have issues with this CORS stuff as well; stuff been working fine for months now without changes *sigh*
![Screenshot_20211129_083932](https://user-images.githubusercontent.com/587487/143820357-3e524ea2-b206-4e26-89b1-1e0174a643fe.jpg)

Trying to log in or make new account but nothing works properly. Not sure how to handle this so far...

**Comment by mofirouz** [comment]
Yep @DreadKnight your specific post is not related to this issue.

**Comment by novabyte** [comment]
@DreadKnight Based on your post it appears your project was working fine but now does not connect due to CORS. Is this correct? If so, what have you changed that could have caused the connectivity differences?

**Comment by DreadKnight** [comment]
@novabyte I edited post before with answer/solution in my case. Basically CORS wasn't an issue, just adding to the confusion. DigitalOcean disabled my droplet cause it can't get money from PayPal by itself, game was saying that login is not valid, not that it couldn't connect to server... at least I didn't wasted days on this like in other lamer scenarios. Tech, 1000 things that can go wrong.

**Comment by andreyrk** [comment]
I'm don't think this should be closed because the dude above mistook his issue for the same as this.
